import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { AuditLogEntry } from '../types';

export interface AuditPdfOptions {
  logs: AuditLogEntry[];
  totalLogCount?: number;
  filterSummary?: string;
  generatedBy?: string;
  generatedRole?: string;
  includeExecutiveSummary?: boolean;
  includeSignatures?: boolean;
  notes?: string;
}

export const generateAuditTrailPdf = (options: AuditPdfOptions): jsPDF => {
  const {
    logs,
    totalLogCount = logs.length,
    filterSummary = 'All Records',
    generatedBy = 'System Operator',
    generatedRole = 'Admin / Compliance Officer',
    includeExecutiveSummary = true,
    includeSignatures = true,
    notes = ''
  } = options;

  // Initialize jsPDF with portrait A4
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 14;
  const contentWidth = pageWidth - margin * 2;

  const now = new Date();
  const dateFormatted = now.toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric'
  });
  const timeFormatted = now.toLocaleTimeString('en-US', {
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
    hour12: true
  });
  const docId = `PCC-MMSU-AUD-${now.getFullYear()}${String(now.getMonth() + 1).padStart(2, '0')}${String(now.getDate()).padStart(2, '0')}-${String(Math.floor(1000 + Math.random() * 9000))}`;

  // ==========================================
  // 1. INSTITUTIONAL HEADER & LOGO / TITLE
  // ==========================================
  let currentY = 16;

  // Government Banner
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7.5);
  doc.setTextColor(100, 116, 139); // slate-500
  doc.text('REPUBLIC OF THE PHILIPPINES  •  DEPARTMENT OF AGRICULTURE', pageWidth / 2, currentY, { align: 'center' });

  currentY += 4.5;
  doc.setFontSize(11.5);
  doc.setTextColor(15, 23, 42); // slate-900
  doc.text('PHILIPPINE CARABAO CENTER AT MARIANO MARCOS STATE UNIVERSITY', pageWidth / 2, currentY, { align: 'center' });

  currentY += 4;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(71, 85, 105); // slate-600
  doc.text('Dairy Processing & Cold Chain Management Facility • Batac City, Ilocos Norte 2906', pageWidth / 2, currentY, { align: 'center' });

  currentY += 5.5;
  // Report Title Badge Bar
  doc.setFillColor(30, 41, 59); // slate-800
  doc.roundedRect(margin, currentY, contentWidth, 7, 1.5, 1.5, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8.5);
  doc.setTextColor(255, 255, 255);
  doc.text('OFFICIAL OPERATIONAL AUDIT TRAIL & COMPLIANCE RECORD', pageWidth / 2, currentY + 4.8, { align: 'center' });

  currentY += 10.5;

  // ==========================================
  // 2. METADATA SUMMARY GRID (4 columns)
  // ==========================================
  doc.setFillColor(248, 250, 252); // slate-50
  doc.setDrawColor(226, 232, 240); // slate-200
  doc.roundedRect(margin, currentY, contentWidth, 14, 1.5, 1.5, 'FD');

  const colWidth = contentWidth / 4;
  const metaY = currentY + 4.2;

  // Col 1: Doc Number
  doc.setFontSize(6.5);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(100, 116, 139);
  doc.text('DOCUMENT CONTROL NO.', margin + 3, metaY);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 41, 59);
  doc.text(docId, margin + 3, metaY + 4.5);

  // Col 2: Date & Time
  doc.setFontSize(6.5);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(100, 116, 139);
  doc.text('GENERATED AT (PST)', margin + colWidth + 3, metaY);
  doc.setFontSize(7.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(30, 41, 59);
  doc.text(`${dateFormatted} ${timeFormatted}`, margin + colWidth + 3, metaY + 4.5);

  // Col 3: Generated By
  doc.setFontSize(6.5);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(100, 116, 139);
  doc.text('PREPARED BY', margin + colWidth * 2 + 3, metaY);
  doc.setFontSize(7.5);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 41, 59);
  doc.text(generatedBy, margin + colWidth * 2 + 3, metaY + 4.5);
  doc.setFontSize(6.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text(`(${generatedRole})`, margin + colWidth * 2 + 3, metaY + 8);

  // Col 4: Scope & Count
  doc.setFontSize(6.5);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(100, 116, 139);
  doc.text('AUDIT LOG SCOPE', margin + colWidth * 3 + 3, metaY);
  doc.setFontSize(7.5);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(79, 70, 229); // indigo-600
  doc.text(`${logs.length} of ${totalLogCount} Entries`, margin + colWidth * 3 + 3, metaY + 4.5);
  doc.setFontSize(6);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text(filterSummary.length > 28 ? filterSummary.substring(0, 26) + '...' : filterSummary, margin + colWidth * 3 + 3, metaY + 8);

  currentY += 17;

  // ==========================================
  // 3. EXECUTIVE SUMMARY METRICS (Optional)
  // ==========================================
  if (includeExecutiveSummary) {
    const invCount = logs.filter(l => l.category === 'inventory' || l.category === 'cold_storage').length;
    const prodCount = logs.filter(l => l.category === 'production').length;
    const warningCount = logs.filter(l => l.severity === 'warning' || l.severity === 'critical').length;
    const infoCount = logs.filter(l => l.severity === 'info' || l.severity === 'success').length;

    doc.setFillColor(241, 245, 249); // slate-100
    doc.setDrawColor(203, 213, 225); // slate-300
    doc.roundedRect(margin, currentY, contentWidth, 12, 1.5, 1.5, 'FD');

    const statWidth = contentWidth / 4;

    const stats = [
      { label: 'TOTAL LOG ENTRIES', val: `${logs.length}`, color: [15, 23, 42] },
      { label: 'INVENTORY / STOCK', val: `${invCount}`, color: [217, 119, 6] },
      { label: 'WIP PRODUCTION', val: `${prodCount}`, color: [79, 70, 229] },
      { label: 'WARNINGS & FLAGS', val: `${warningCount}`, color: [225, 29, 72] }
    ];

    stats.forEach((s, idx) => {
      const sx = margin + idx * statWidth + 4;
      doc.setFontSize(6);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(100, 116, 139);
      doc.text(s.label, sx, currentY + 3.8);

      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(s.color[0], s.color[1], s.color[2]);
      doc.text(s.val, sx, currentY + 9);
    });

    currentY += 15;
  }

  // ==========================================
  // 4. AUDIT LOGS TABLE VIA AUTOTABLE
  // ==========================================
  const tableData = logs.map((log, idx) => {
    // Format timestamp
    const ts = log.timestamp.replace(' PST', '').trim();
    
    // Details string
    let detailsText = log.description;
    const extras: string[] = [];
    if (log.details?.itemOrBatch) extras.push(`Ref: ${log.details.itemOrBatch}`);
    if (log.details?.quantity !== undefined) extras.push(`Qty: ${log.details.quantity} ${log.details.unit || ''}`);
    if (log.details?.previousValue !== undefined && log.details?.newValue !== undefined) {
      extras.push(`Delta: [${log.details.previousValue}] -> [${log.details.newValue}]`);
    }
    if (log.details?.reason) extras.push(`Reason: ${log.details.reason}`);
    if (log.details?.referenceId) extras.push(`PO/Tx: ${log.details.referenceId}`);

    if (extras.length > 0) {
      detailsText += `\n(${extras.join(' | ')})`;
    }

    const subsystemAndAction = `${log.subsystem.toUpperCase()}\n${log.action}`;
    const operator = `${log.userName}\n(${log.terminalOrStation || log.userRole})`;
    const severity = log.severity.toUpperCase();

    return [
      String(idx + 1),
      ts,
      subsystemAndAction,
      detailsText,
      operator,
      severity
    ];
  });

  autoTable(doc, {
    startY: currentY,
    head: [['#', 'Timestamp', 'Subsystem / Action', 'Event Description & Provenance Details', 'Operator / Station', 'Severity']],
    body: tableData,
    theme: 'striped',
    margin: { left: margin, right: margin },
    headStyles: {
      fillColor: [30, 41, 59], // slate-800
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 7.5,
      halign: 'left',
      cellPadding: 2.2
    },
    styles: {
      font: 'helvetica',
      fontSize: 7,
      cellPadding: 2,
      textColor: [30, 41, 59],
      lineColor: [226, 232, 240],
      lineWidth: 0.2,
      overflow: 'linebreak'
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252] // slate-50
    },
    columnStyles: {
      0: { cellWidth: 8, halign: 'center', fontStyle: 'bold' },
      1: { cellWidth: 26, fontStyle: 'bold' },
      2: { cellWidth: 32, fontStyle: 'bold' },
      3: { cellWidth: 'auto' },
      4: { cellWidth: 30 },
      5: { cellWidth: 16, halign: 'center', fontStyle: 'bold' }
    },
    didParseCell: (data) => {
      // Color code severity in the severity column
      if (data.section === 'body' && data.column.index === 5) {
        const val = String(data.cell.raw).toLowerCase();
        if (val.includes('critical')) {
          data.cell.styles.textColor = [190, 18, 60]; // rose-700
          data.cell.styles.fontStyle = 'bold';
        } else if (val.includes('warning')) {
          data.cell.styles.textColor = [180, 83, 9]; // amber-700
          data.cell.styles.fontStyle = 'bold';
        } else if (val.includes('success')) {
          data.cell.styles.textColor = [15, 118, 110]; // teal-700
        } else {
          data.cell.styles.textColor = [71, 85, 105]; // slate-600
        }
      }
    }
  });

  // Get final Y after table
  const lastAutoTable = (doc as any).lastAutoTable;
  let finalY = lastAutoTable ? lastAutoTable.finalY + 8 : currentY + 40;

  // Check if we have enough space on the current page for notes & signatures
  const spaceNeeded = includeSignatures ? 45 : 20;
  if (finalY + spaceNeeded > pageHeight - 18) {
    doc.addPage();
    finalY = 20;
  }

  // Optional Notes section
  if (notes.trim()) {
    doc.setFontSize(7);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(71, 85, 105);
    doc.text('AUDIT COMPLIANCE NOTES / OBSERVATIONS:', margin, finalY);

    doc.setFont('helvetica', 'normal');
    doc.setTextColor(30, 41, 59);
    const splitNotes = doc.splitTextToSize(notes, contentWidth);
    doc.text(splitNotes, margin, finalY + 4);
    finalY += (splitNotes.length * 3.5) + 6;
  }

  // ==========================================
  // 5. REGULATORY SIGN-OFF & VERIFICATION BLOCK
  // ==========================================
  if (includeSignatures) {
    doc.setDrawColor(203, 213, 225);
    doc.line(margin, finalY, pageWidth - margin, finalY);
    finalY += 4;

    doc.setFontSize(7);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(71, 85, 105);
    doc.text('REGULATORY VERIFICATION & RECORD-KEEPING ENDORSEMENT', margin, finalY);
    finalY += 3.5;

    doc.setFontSize(6);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(148, 163, 184);
    doc.text('In accordance with Philippine Carabao Center Quality Assurance protocols and ISO 25010 operational accountability standards:', margin, finalY);
    finalY += 8;

    const signColWidth = contentWidth / 3;

    // Signatory 1
    const s1X = margin;
    doc.setFontSize(6.5);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(100, 116, 139);
    doc.text('1. AUDIT LOG EXTRACTED BY:', s1X, finalY);
    doc.setDrawColor(71, 85, 105);
    doc.line(s1X, finalY + 12, s1X + signColWidth - 8, finalY + 12);
    doc.setFontSize(7.5);
    doc.setTextColor(15, 23, 42);
    doc.text(generatedBy, s1X, finalY + 15.5);
    doc.setFontSize(6);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 116, 139);
    doc.text('System Custodian / Records Officer', s1X, finalY + 18.5);
    doc.text('Date: _________________________', s1X, finalY + 22);

    // Signatory 2
    const s2X = margin + signColWidth;
    doc.setFontSize(6.5);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(100, 116, 139);
    doc.text('2. QUALITY & INTEGRITY VERIFIED BY:', s2X, finalY);
    doc.setDrawColor(71, 85, 105);
    doc.line(s2X, finalY + 12, s2X + signColWidth - 8, finalY + 12);
    doc.setFontSize(7.5);
    doc.setTextColor(15, 23, 42);
    doc.text('QA & Food Safety Inspector', s2X, finalY + 15.5);
    doc.setFontSize(6);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 116, 139);
    doc.text('PCC-MMSU Laboratory Section', s2X, finalY + 18.5);
    doc.text('Date: _________________________', s2X, finalY + 22);

    // Signatory 3
    const s3X = margin + signColWidth * 2;
    doc.setFontSize(6.5);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(100, 116, 139);
    doc.text('3. NOTED & OFFICIALLY FILED BY:', s3X, finalY);
    doc.setDrawColor(71, 85, 105);
    doc.line(s3X, finalY + 12, s3X + signColWidth - 8, finalY + 12);
    doc.setFontSize(7.5);
    doc.setTextColor(15, 23, 42);
    doc.text('Center Director / Plant Manager', s3X, finalY + 15.5);
    doc.setFontSize(6);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 116, 139);
    doc.text('Mariano Marcos State University', s3X, finalY + 18.5);
    doc.text('Date: _________________________', s3X, finalY + 22);
  }

  // ==========================================
  // 6. MULTI-PAGE NUMBERING & COMPLIANCE FOOTER
  // ==========================================
  const totalPages = (doc.internal as any).getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    const footerY = pageHeight - 7;

    doc.setDrawColor(226, 232, 240);
    doc.setLineWidth(0.3);
    doc.line(margin, footerY - 2.5, pageWidth - margin, footerY - 2.5);

    doc.setFontSize(6);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(148, 163, 184); // slate-400
    doc.text(
      `DairySync Operational Provenance System • Doc ID: ${docId} • Certified ISO 25010 Log`,
      margin,
      footerY
    );

    doc.setFont('helvetica', 'bold');
    doc.text(
      `Page ${i} of ${totalPages}`,
      pageWidth - margin,
      footerY,
      { align: 'right' }
    );
  }

  return doc;
};

export const downloadAuditTrailPdf = (options: AuditPdfOptions, filename?: string): void => {
  const doc = generateAuditTrailPdf(options);
  const now = new Date();
  const dateStr = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}`;
  const actualFilename = filename || `PCC-MMSU_Audit_Trail_Report_${dateStr}.pdf`;
  doc.save(actualFilename);
};
